# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 746)
        MainWindow.setStyleSheet("QWidget{\n"
"background-color:#E3F6F5;\n"
"}\n"
"QPushButton{\n"
"background-color:#E3F6F5;\n"
"color:#272343;font-size:24px;\n"
"border:1px solid #BAE8E8;width:50;\n"
"height:110;\n"
"}\n"
"QLineEdit{\n"
"background-color:#E3F6F5;\n"
"color:#272343;font-size:24px;\n"
"border:none;\n"
"height: 70px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#BAE8E8;\n"
"}\n"
"#result {\n"
"font-size: 35px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Exercise = QtWidgets.QLineEdit(self.centralwidget)
        self.Exercise.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Exercise.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Exercise.setReadOnly(True)
        self.Exercise.setObjectName("Exercise")
        self.verticalLayout.addWidget(self.Exercise)
        self.result = QtWidgets.QLineEdit(self.centralwidget)
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.devision = QtWidgets.QPushButton(self.centralwidget)
        self.devision.setObjectName("devision")
        self.gridLayout.addWidget(self.devision, 5, 3, 1, 1)
        self.umn = QtWidgets.QPushButton(self.centralwidget)
        self.umn.setObjectName("umn")
        self.gridLayout.addWidget(self.umn, 4, 3, 1, 1)
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 3, 3, 1, 1)
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setObjectName("dot")
        self.gridLayout.addWidget(self.dot, 6, 2, 1, 1)
        self.num3 = QtWidgets.QPushButton(self.centralwidget)
        self.num3.setObjectName("num3")
        self.gridLayout.addWidget(self.num3, 5, 2, 1, 1)
        self.num6 = QtWidgets.QPushButton(self.centralwidget)
        self.num6.setObjectName("num6")
        self.gridLayout.addWidget(self.num6, 4, 2, 1, 1)
        self.num9 = QtWidgets.QPushButton(self.centralwidget)
        self.num9.setObjectName("num9")
        self.gridLayout.addWidget(self.num9, 3, 2, 1, 1)
        self.num5 = QtWidgets.QPushButton(self.centralwidget)
        self.num5.setObjectName("num5")
        self.gridLayout.addWidget(self.num5, 4, 1, 1, 1)
        self.num2 = QtWidgets.QPushButton(self.centralwidget)
        self.num2.setObjectName("num2")
        self.gridLayout.addWidget(self.num2, 5, 1, 1, 1)
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 6, 1, 1, 1)
        self.doublezero = QtWidgets.QPushButton(self.centralwidget)
        self.doublezero.setObjectName("doublezero")
        self.gridLayout.addWidget(self.doublezero, 6, 0, 1, 1)
        self.num8 = QtWidgets.QPushButton(self.centralwidget)
        self.num8.setObjectName("num8")
        self.gridLayout.addWidget(self.num8, 3, 1, 1, 1)
        self.num4 = QtWidgets.QPushButton(self.centralwidget)
        self.num4.setObjectName("num4")
        self.gridLayout.addWidget(self.num4, 4, 0, 1, 1)
        self.num1 = QtWidgets.QPushButton(self.centralwidget)
        self.num1.setObjectName("num1")
        self.gridLayout.addWidget(self.num1, 5, 0, 1, 1)
        self.num7 = QtWidgets.QPushButton(self.centralwidget)
        self.num7.setObjectName("num7")
        self.gridLayout.addWidget(self.num7, 3, 0, 1, 1)
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setObjectName("equal")
        self.gridLayout.addWidget(self.equal, 6, 3, 1, 1)
        self.koren = QtWidgets.QPushButton(self.centralwidget)
        self.koren.setObjectName("koren")
        self.gridLayout.addWidget(self.koren, 2, 2, 1, 1)
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 2, 3, 1, 1)
        self.inDouble = QtWidgets.QPushButton(self.centralwidget)
        self.inDouble.setObjectName("inDouble")
        self.gridLayout.addWidget(self.inDouble, 2, 1, 1, 1)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator++"))
        MainWindow.setWindowIcon(QtGui.QIcon("calculator.png"))
        self.devision.setText(_translate("MainWindow", "/"))
        self.umn.setText(_translate("MainWindow", "*"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.dot.setText(_translate("MainWindow", "."))
        self.num3.setText(_translate("MainWindow", "3"))
        self.num6.setText(_translate("MainWindow", "6"))
        self.num9.setText(_translate("MainWindow", "9"))
        self.num5.setText(_translate("MainWindow", "5"))
        self.num2.setText(_translate("MainWindow", "2"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.doublezero.setText(_translate("MainWindow", "00"))
        self.num8.setText(_translate("MainWindow", "8"))
        self.num4.setText(_translate("MainWindow", "4"))
        self.num1.setText(_translate("MainWindow", "1"))
        self.num7.setText(_translate("MainWindow", "7"))
        self.equal.setText(_translate("MainWindow", "="))
        self.koren.setText(_translate("MainWindow", "√"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.inDouble.setText(_translate("MainWindow", "^2"))
        self.clear.setText(_translate("MainWindow", "AC"))
